# Generated by Django 3.2.19 on 2023-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_add_new_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productunique',
            old_name='name',
            new_name='title',
        ),
    ]
