# Generated by Django 3.2.19 on 2023-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_change_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunique',
            name='unique',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
